-- RenfyGrid -- 0024_guides_2_5_6_checklists.sql
-- Formatos de las Guias 2, 5 y 6 de Municipios Azules que son LISTAS de
-- verificacion (2026-10-05, a pedido del usuario: "carga los formatos de las
-- guias 2, 5 y 6"). Textos literales de las guias (Clientes\ARCA\Guia2,
-- Guia5, Guia6). Los formatos que son TABLAS o MATRICES a llenar (G2: 7A,
-- 7D, 7E, 7F, 7G, 7I; G5: mapa de microcuenca, plan de campana; G6: 7A-7E,
-- 7G) no son listas y no se cargan aqui (ver docs/04-plan-sprints.md SS11.4b).
--
-- Criterio de hallazgos y prioridades: las guias no los fijan. Se usa el
-- mismo criterio de los formatos ya cargados (respuesta negativa = alta;
-- "no sabemos" / "en proceso" = media). Es dato del paquete, ajustable.
--
-- Novedades del modelo:
--   kind 'products'  -- pasaporte de productos de cada guia (Listo / Falta).
--   ask_note         -- en una entrada de la escala: pedir observacion aunque
--                       no genere hallazgo (p. ej. "No" / "N/A" de los 25
--                       requisitos del proyecto: hay que explicar que falta,
--                       pero un documento pendiente no es una falla del sistema).

ALTER TABLE checklist_template DROP CONSTRAINT checklist_template_kind_check;
ALTER TABLE checklist_template ADD CONSTRAINT checklist_template_kind_check
    CHECK (kind IN ('inspection', 'traffic_light', 'self_assessment', 'products'));

INSERT INTO checklist_template (id, pack_id, kind, title, purpose, scale, items, stage_code, frequency_days) VALUES

-- ── Guia 2 · Gobernanza, organizacion y marco legal ───────────────────
('MA-G2-START', 'EC-MUNICIPIOS-AZULES', 'self_assessment', 'Verificación inicial — Guía 2 (gobernanza y marco legal)',
 'Respondamos antes de iniciar. No hay respuestas correctas o incorrectas: estas preguntas muestran desde dónde empieza la comunidad.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "somewhat", "label": "Más o menos", "finding": false, "score": 1},
   {"code": "no", "label": "No", "finding": false, "score": 0}]',
 '[{"key": "knows_who_decides", "text": "¿Sabemos quién toma las decisiones principales en nuestra JAAPS?"},
   {"key": "roles_known", "text": "¿Cada cargo conoce sus funciones y a quién debe rendir cuentas?"},
   {"key": "legal_basics", "text": "¿Tenemos personería jurídica, estatuto y directiva registrada?"},
   {"key": "aua_current", "text": "¿Sabemos si la AUA y los demás documentos están vigentes?"},
   {"key": "yearly_accountability", "text": "¿La asamblea recibe una rendición de cuentas al menos una vez al año?"},
   {"key": "knows_first_procedure", "text": "¿Sabemos qué trámite o instrumento debemos actualizar primero?"}]',
 'G2', NULL),

('MA-G2-7B', 'EC-MUNICIPIOS-AZULES', 'inspection', '7B. Lista para preparar y registrar una asamblea',
 'Se usa en la Actividad participativa 2. Marquen cada casilla durante la preparación y el registro de la asamblea.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "missing", "label": "Falta", "finding": true, "finding_priority": "high", "score": 0},
   {"code": "unknown", "label": "No sabemos", "finding": true, "finding_priority": "medium", "score": 0}]',
 '[{"key": "call_complete", "text": "Convocatoria indica tipo, fecha, hora, lugar y orden del día."},
   {"key": "call_published", "text": "La convocatoria se difundió según el estatuto."},
   {"key": "roll_signed", "text": "El padrón sencillo está fechado y firmado; la lista de asistencia está disponible."},
   {"key": "quorum_checked", "text": "Se verificó el quórum antes de decidir."},
   {"key": "agreements_owned", "text": "Cada acuerdo tiene responsable y plazo."},
   {"key": "minutes_signed", "text": "El acta registra votaciones y se encuentra firmada."}]',
 'G2', NULL),

('MA-G2-7C', 'EC-MUNICIPIOS-AZULES', 'inspection', '7C. Lista de verificación legal e institucional',
 'Revisen los documentos que realmente están en el archivo; no respondan solo de memoria.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "missing", "label": "Falta", "finding": true, "finding_priority": "high", "score": 0},
   {"code": "unknown", "label": "No sabemos", "finding": true, "finding_priority": "medium", "score": 0}]',
 '[{"key": "legal_personality", "text": "Personería jurídica disponible y archivada."},
   {"key": "bylaws_current", "text": "Estatuto vigente y conocido por la directiva."},
   {"key": "internal_rules", "text": "Reglamento interno aprobado y actualizado."},
   {"key": "board_registered", "text": "Directiva registrada ante el Ministerio del Ambiente y Energía (MAE)."},
   {"key": "aua_current", "text": "AUA vigente y correspondiente a la fuente utilizada."},
   {"key": "user_roll_updated", "text": "Padrón de personas usuarias actualizado."},
   {"key": "minutes_book", "text": "Libro de actas completo y firmado."},
   {"key": "technical_archive", "text": "Archivo técnico con planos, análisis y registros de operación y mantenimiento."},
   {"key": "budget_poa_approved", "text": "Presupuesto y POA aprobados."},
   {"key": "tariff_reviewed", "text": "Tarifa revisada con sustento técnico."},
   {"key": "accountability_presented", "text": "Rendición de cuentas presentada."},
   {"key": "claims_register", "text": "Registro de reclamos en funcionamiento."}]',
 'G2', NULL),

('MA-G2-7H', 'EC-MUNICIPIOS-AZULES', 'products', '7H. Productos finales — Guía 2',
 'Se completa al terminar el taller. Cada producto debe venir de la actividad o del contenido indicado.',
 '[{"code": "ready", "label": "Listo", "finding": false, "score": 2},
   {"code": "pending", "label": "Falta", "finding": false, "ask_note": true, "score": 0}]',
 '[{"key": "org_chart", "text": "Organigrama y roles revisados (Actividad 1 · formato 7A)"},
   {"key": "assembly_minutes", "text": "Asamblea simulada y borrador de acta (Actividad 2 · formato 7B · Anexo 2)"},
   {"key": "legal_diagnosis", "text": "Diagnóstico legal y de instrumentos (Actividad 3 · formato 7C)"},
   {"key": "user_roll", "text": "Padrón de personas usuarias actualizado (Bloque 2 · formato 7I)"},
   {"key": "update_route", "text": "Ruta de actualización priorizada (Actividad 3 · formato 7D)"},
   {"key": "alliance_proposal", "text": "Propuesta inicial de alianza (Actividad 4 · formato 7E)"},
   {"key": "transparency_plan", "text": "Plan de transparencia (Actividad 5 · formato 7F)"},
   {"key": "governance_plan", "text": "Plan mínimo de gobernanza (Sección 4)"},
   {"key": "adapted_models", "text": "Modelos adaptados a la JAAPS (Anexos 1, 2 y 3)"}]',
 'G2', NULL),

-- ── Guia 5 · Ambiente, agua segura y WASH ─────────────────────────────
('MA-G5-START', 'EC-MUNICIPIOS-AZULES', 'self_assessment', 'Verificación inicial — Guía 5 (ambiente, agua segura y WASH)',
 'Antes de iniciar el taller respondamos esta verificación inicial. No hay respuestas incorrectas: nos ayuda a saber desde dónde empezamos.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "somewhat", "label": "Más o menos", "finding": false, "score": 1},
   {"code": "no", "label": "No", "finding": false, "score": 0}]',
 '[{"key": "knows_source", "text": "¿Sabemos de dónde viene el agua que tomamos?"},
   {"key": "source_protected", "text": "¿La fuente está protegida de animales, basura y agroquímicos?"},
   {"key": "home_treatment", "text": "¿Sabemos cómo tratar y guardar agua segura en casa?"},
   {"key": "handwashing", "text": "¿Nos lavamos las manos en los momentos críticos?"},
   {"key": "campaigns_done", "text": "¿Hemos realizado campañas de higiene o protección de fuentes?"},
   {"key": "knows_diseases", "text": "¿Sabemos qué enfermedades se relacionan con el agua y el saneamiento?"}]',
 'G5', NULL),

('MA-G5-5A', 'EC-MUNICIPIOS-AZULES', 'inspection', '5A. Protección de fuente',
 'Lista de la ficha de diagnóstico ambiental y WASH. Conviene usarla durante el taller, junto a cada tema, y dejarla en la comunidad como herramienta de consulta.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "in_progress", "label": "En proceso", "finding": true, "finding_priority": "medium", "score": 1},
   {"code": "no", "label": "No", "finding": true, "finding_priority": "high", "score": 0}]',
 '[{"key": "intake_fenced", "text": "Captación con cerco y señalización.", "component_service": "water"},
   {"key": "protection_zone_clear", "text": "Zona de protección sin animales ni cultivos contaminantes.", "component_service": "water"},
   {"key": "native_reforestation", "text": "Actividades de reforestación con plantas nativas.", "component_service": "water"},
   {"key": "no_agrochemicals", "text": "Sin agroquímicos cerca de la fuente.", "component_service": "water"},
   {"key": "no_waste_burning", "text": "Sin basura ni quemas cerca de la captación.", "component_service": "water"},
   {"key": "community_vigilance", "text": "Comunidad participa en limpieza y vigilancia.", "component_service": "water"}]',
 'G5', NULL),

('MA-G5-5B', 'EC-MUNICIPIOS-AZULES', 'inspection', '5B. Agua segura y saneamiento',
 'Lista de la ficha de diagnóstico ambiental y WASH: agua segura en el hogar y saneamiento.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "in_progress", "label": "En proceso", "finding": true, "finding_priority": "medium", "score": 1},
   {"code": "no", "label": "No", "finding": true, "finding_priority": "high", "score": 0}]',
 '[{"key": "users_treat_water", "text": "Usuarios saben hervir o tratar agua cuando sea necesario."},
   {"key": "covered_containers", "text": "Recipientes con tapa y limpios."},
   {"key": "household_sanitation", "text": "Familias con baño, letrina o solución sanitaria.", "component_service": "sanitation"},
   {"key": "no_discharge_to_streams", "text": "Aguas residuales no se vierten a quebradas.", "component_service": "sanitation"},
   {"key": "septic_far_from_sources", "text": "Pozos sépticos alejados de fuentes.", "component_service": "sanitation"},
   {"key": "sanitation_maintained", "text": "Mantenimiento de saneamiento realizado.", "component_service": "sanitation"}]',
 'G5', NULL),

('MA-G5-5C', 'EC-MUNICIPIOS-AZULES', 'inspection', '5C. Higiene y salud',
 'Lista de la ficha de diagnóstico ambiental y WASH: higiene, salud y comunicación.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "in_progress", "label": "En proceso", "finding": true, "finding_priority": "medium", "score": 1},
   {"code": "no", "label": "No", "finding": true, "finding_priority": "high", "score": 0}]',
 '[{"key": "handwashing_campaigns", "text": "Campañas de lavado de manos realizadas."},
   {"key": "school_water_soap", "text": "Escuela cuenta con agua y jabón."},
   {"key": "families_know_dci", "text": "Familias conocen relación entre agua, diarrea y DCI."},
   {"key": "quality_alerts_communicated", "text": "Se comunican alertas de calidad de agua."},
   {"key": "food_washed_safe_water", "text": "Se promueve lavar alimentos con agua segura."},
   {"key": "animals_out_of_kitchen", "text": "Se mantiene animales fuera de cocina y recipientes de agua."}]',
 'G5', NULL),

('MA-G5-WASH', 'EC-MUNICIPIOS-AZULES', 'self_assessment', 'Ficha de diagnóstico ambiental y WASH',
 'Califique cada aspecto de 1 (muy mal) a 5 (muy bien) según la situación actual y anote la acción. Una calificación de 1 o 2 queda como hallazgo.',
 '[{"code": "1", "label": "1", "finding": true, "finding_priority": "high", "score": 1},
   {"code": "2", "label": "2", "finding": true, "finding_priority": "medium", "score": 2},
   {"code": "3", "label": "3", "finding": false, "ask_note": true, "score": 3},
   {"code": "4", "label": "4", "finding": false, "score": 4},
   {"code": "5", "label": "5", "finding": false, "score": 5}]',
 '[{"key": "intake_protected", "text": "Captación protegida"},
   {"key": "waste_near_source", "text": "Basura cerca de fuente"},
   {"key": "animals_near_water", "text": "Animales en cocina o cerca de agua"},
   {"key": "stored_water_covered", "text": "Agua almacenada con tapa"},
   {"key": "handwashing", "text": "Lavado de manos"},
   {"key": "wastewater_management", "text": "Manejo de aguas residuales"}]',
 'G5', NULL),

('MA-G5-HOME', 'EC-MUNICIPIOS-AZULES', 'self_assessment', 'Práctica de agua segura en el hogar',
 'Actividad participativa: demostración de agua segura en el hogar. ¿La sabemos hacer? Anote qué falta mejorar.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "no", "label": "No", "finding": false, "ask_note": true, "score": 0}]',
 '[{"key": "boil", "text": "Hervir agua"},
   {"key": "chlorinate", "text": "Clorar con orientación"},
   {"key": "filter_turbid", "text": "Filtrar agua turbia"},
   {"key": "store_covered", "text": "Guardar agua tapada"}]',
 'G5', NULL),

('MA-G5-PRODUCTS', 'EC-MUNICIPIOS-AZULES', 'products', 'Productos finales — Guía 5',
 'Producto final de esta guía.',
 '[{"code": "complete", "label": "Completo", "finding": false, "score": 2},
   {"code": "pending", "label": "Pendiente", "finding": false, "ask_note": true, "score": 0}]',
 '[{"key": "watershed_map", "text": "Mapa de fuente y microcuenca"},
   {"key": "protection_actions", "text": "Acciones de protección ambiental"},
   {"key": "safe_water_demo", "text": "Demostración de agua segura"},
   {"key": "handwashing_practice", "text": "Práctica de lavado de manos"},
   {"key": "campaign_plan", "text": "Plan de campaña comunitaria"}]',
 'G5', NULL),

-- ── Guia 6 · Plan de Mejora y formulacion de proyectos ────────────────
('MA-G6-START', 'EC-MUNICIPIOS-AZULES', 'self_assessment', 'Verificación inicial — Guía 6 (Plan de Mejora y proyectos)',
 'Respondamos antes de iniciar: estas preguntas muestran desde dónde empieza la comunidad.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "somewhat", "label": "Más o menos", "finding": false, "score": 1},
   {"code": "no", "label": "No", "finding": false, "score": 0}]',
 '[{"key": "has_products_g1_g5", "text": "¿Contamos con los productos de las guías 1 a 5?"},
   {"key": "knows_valid_data", "text": "¿Sabemos cuáles datos siguen vigentes y cuáles deben verificarse?"},
   {"key": "knows_problems_causes", "text": "¿Tenemos claros los problemas principales y sus causas?"},
   {"key": "compares_alternatives", "text": "¿Sabemos comparar alternativas de solución?"},
   {"key": "goal_and_indicator", "text": "¿Podemos formular una meta y un indicador?"},
   {"key": "knows_approval", "text": "¿Conocemos cómo se aprueba y se da seguimiento al plan?"}]',
 'G6', NULL),

('MA-G6-7F', 'EC-MUNICIPIOS-AZULES', 'inspection', '7F. Lista de verificación para gestionar proyectos de agua potable y saneamiento',
 'Marque una sola opción por requisito y explique en observaciones qué documento existe, quién lo tiene, qué falta completar o por qué no aplica. No todos los proyectos requieren la misma documentación: confirme qué documentos aplican antes de iniciar estudios o comprometer recursos.',
 '[{"code": "yes", "label": "Sí", "finding": false, "score": 2},
   {"code": "no", "label": "No", "finding": false, "ask_note": true, "score": 0},
   {"code": "na", "label": "N/A", "finding": false, "ask_note": true, "score": 2}]',
 '[{"key": "environmental_regularization", "text": "Regularización ambiental (permiso, registro, licencia, ficha ambiental o PMA, cuando corresponda)"},
   {"key": "enabling_documents", "text": "Documentos habilitantes (autorización de uso del agua, escrituras, servidumbres u otros)"},
   {"key": "technical_memory", "text": "Memoria técnica o diagnóstico del sistema y alternativas de solución"},
   {"key": "surveys_user_roll", "text": "Encuestas y padrón simple de personas usuarias, denominado catastro en algunos instrumentos oficiales"},
   {"key": "water_quality_analysis", "text": "Análisis de la calidad del agua"},
   {"key": "soil_studies", "text": "Estudios de suelos (cuando sean necesarios)"},
   {"key": "topography", "text": "Topografía del área del proyecto (cuando aplique)"},
   {"key": "technical_calculations", "text": "Estudios y cálculos técnicos (hidráulicos, hidrológicos, estructurales u otros)"},
   {"key": "project_budget", "text": "Presupuesto referencial o definitivo del proyecto"},
   {"key": "technical_specifications", "text": "Especificaciones técnicas de la obra"},
   {"key": "socioeconomic_study", "text": "Estudio socioeconómico y financiero"},
   {"key": "project_plans", "text": "Planos del proyecto"},
   {"key": "legal_documentation", "text": "Documentación legal de la JAAPS (personería jurídica, estatuto, reglamento y directiva vigente)"},
   {"key": "community_socialization", "text": "Documentación de socialización con la comunidad"},
   {"key": "community_minutes", "text": "Actas y acuerdos comunitarios (servidumbres, aprobación del proyecto u otros)"},
   {"key": "management_model", "text": "Modelo de gestión del sistema"},
   {"key": "community_development_plan", "text": "Plan de desarrollo comunitario y participación social"},
   {"key": "tariff_study", "text": "Estudio tarifario y aprobación de la tarifa"},
   {"key": "om_manual", "text": "Manual de operación y mantenimiento"},
   {"key": "materials_debris_plan", "text": "Plan para provisión de materiales y disposición de escombros (cuando aplique)"},
   {"key": "risk_management", "text": "Gestión de riesgos y vulnerabilidad del sistema"},
   {"key": "occupational_safety", "text": "Prevención de riesgos laborales y seguridad ocupacional"},
   {"key": "knowledge_transfer", "text": "Plan de transferencia del conocimiento y tecnología (cuando corresponda)"},
   {"key": "environmental_impacts", "text": "Análisis de impactos ambientales"},
   {"key": "executive_summary", "text": "Resumen ejecutivo del proyecto"}]',
 'G6', NULL),

('MA-G6-7H', 'EC-MUNICIPIOS-AZULES', 'products', '7H. Productos finales — Guía 6',
 'Se usa al cierre de la guía y en la asamblea de aprobación. La asamblea valida y aprueba.',
 '[{"code": "complete", "label": "Completo", "finding": false, "score": 2},
   {"code": "pending", "label": "Pendiente", "finding": false, "ask_note": true, "score": 0}]',
 '[{"key": "consolidated_inputs", "text": "Consolidado de insumos de las guías 1 a 5 (Actividad 1 · 7A)"},
   {"key": "diagnosis_prioritization", "text": "Diagnóstico y priorización por componentes (Actividad 2 · 7B)"},
   {"key": "selected_alternatives", "text": "Alternativas seleccionadas (Actividad 3 · 7C)"},
   {"key": "improvement_plan", "text": "Plan de Mejora integral (Actividad 4 · 7D)"},
   {"key": "budget_schedule", "text": "Presupuesto y cronograma (Actividad 4 · 7E)"},
   {"key": "project_profile", "text": "Perfil comunitario de proyecto (Actividad 5 · 7F)"},
   {"key": "tracking_board", "text": "Tablero de seguimiento (Actividad 6 · 7G)"},
   {"key": "approval_minutes", "text": "Acta de aprobación en asamblea (Actividad 6)"},
   {"key": "requirements_checklist", "text": "Lista de verificación de requisitos del proyecto (formato 7F)"}]',
 'G6', NULL),

('MA-G6-SUBMIT', 'EC-MUNICIPIOS-AZULES', 'products', 'Lista mínima para una presentación formal del Plan de Mejora',
 'Anexo A de la Guía 6. Antes de presentar, confirme con la Autoridad Única del Agua el acto administrativo, el formato oficial vigente, el plazo, los anexos obligatorios, el canal y la unidad responsable.',
 '[{"code": "ready", "label": "Listo", "finding": false, "score": 2},
   {"code": "pending", "label": "Falta", "finding": false, "ask_note": true, "score": 0}]',
 '[{"key": "authority_request", "text": "Requerimiento u oficio de la autoridad"},
   {"key": "official_format", "text": "Copia o enlace del formato oficial vigente"},
   {"key": "plan_approved", "text": "Plan de Mejora aprobado por la asamblea"},
   {"key": "diagnosis_matrix", "text": "Matriz de diagnóstico y priorización"},
   {"key": "alternatives_activities", "text": "Alternativas y actividades seleccionadas"},
   {"key": "budget_sources", "text": "Presupuesto y fuentes de financiamiento"},
   {"key": "schedule", "text": "Cronograma"},
   {"key": "indicators_board", "text": "Indicadores y tablero de seguimiento"},
   {"key": "approval_attendance", "text": "Acta de aprobación y lista de asistencia"},
   {"key": "requested_evidence", "text": "Evidencias técnicas, legales, financieras y ambientales solicitadas"},
   {"key": "submission_receipt", "text": "Comprobante de presentación y número de trámite"}]',
 'G6', NULL);
